### PR TITLE
Move some of the mypy tests over.

### PR DESCRIPTION
**Pull request by euresti**
Ported some of the tests from mypy over here.   There are still a couple of issues so I've "skipped" some tests.
1. The plugin tester doesn't support changing the python version.  I'll put up a PR over there to fix the issue soon.
2. Something is weird with the inheritance which isn't present in the mypy test.  Very strange.  

It turns out these tests are actually better over here because they combine the stubs with the plugin.  The tests in mypy use the plugin but use some "basic" stubs that haven't been updated since ... who knows when.

This test does add around 30seconds to the test run.  Maybe we can trim some tests later if we feel this is too exhaustive.

I don't know why coverage failed.  I didn't touch those files.  Weird.

# Pull Request Check List

This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.  If your pull request is a documentation fix or a trivial typo, feel free to delete the whole thing.

- [x] Added **tests** for changed code.
- [x] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/strategies.py).
- [x] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [ ] ...and used in the stub test file `tests/typing_example.py`.
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in our [``__init__.py``](https://github.com/python-attrs/attrs/blob/master/src/attr/__init__.py) file.
- [ ] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/master/changelog.d).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by euresti** [comment]
I don't know why coverage is failing.  I didn't change any files that should affect it.

**Comment by hynek** [comment]
Probably just codecov failing to upload again.

**Comment by hynek** [comment]
So I don't feel like I can meaningfully review this…since it's all new and shit, I guess we'll just merge it and look how'll feel over time?

**Comment by euresti** [comment]
Well, you could look at the tests and see if the code that is in there makes sense.  Basically, the tests are here's some python code, run mypy on it, here's what we expect it to say.  Though all these tests were in mypy already so nothing new here.

**Comment by euresti** [comment]
But I don't know if anybody else interested too, @ambv maybe?

**Review by hynek — APPROVED** [review]
yolo

**Pull request merged**
