### PR TITLE
Added support for keyword-only arguments on Python 3+

### PR DESCRIPTION
**Pull request by malinoff**
# Pull Request Check List

- [x] Added **tests** for changed code.
- [x] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/utils.py).
- [x] Updated **documentation** for changed code.
- [x] Documentation in `.rst` files is written using [semantic newlines](http://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
- [x] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/master/changelog.d).

Please, correct me if I checked something wrong.

### CODE REVIEW

**Comment by malinoff** [comment]
@hynek I decided to go with a dedicated `attr.ib()` argument for the sake of simplicity: I don't like to overload `init` with more options than a simple on/off switch.
But if you think this is a bad API, let's discuss a better approach.

**Comment by hynek** [comment]
Wow, thanks for tackling this!

Before I dive deeper and start nitpicking:

- please make it `kw_only` it’s more readable and I’d like to set the precedent of not smashing words together German-style. :)
- There was an example of how to solve this problem for Python 2: https://github.com/python-attrs/attrs/issues/106#issuecomment-315690579 and I think it’s worth pursuing.  No need to make the feature Python 3-only and it should be rather easy to add?  If you run into any problems implementing it, we can always back out again.

**Comment by malinoff** [comment]
> * please make it `kw_only`

Done.

> * There was an example of how to solve this problem for Python 2: https://github.com/python-attrs/attrs/issues/106#issuecomment-315690579  and I think it’s worth pursuing. No need to make the feature Python 3-only and it should be rather easy to add? If you run into any problems implementing it, we can always back out again.

Or we could make Python 3 transition slightly faster :) With no jokes, although I'm against of supporting such unique Python 3 features on Python 2 I'll try to implement this fallback anyway.

**Comment by hynek** [comment]
Ohhh…so you implemented it only on a per-attribute basis instead of per-class?

**Comment by hynek** [comment]
(JFTR I have zero qualms leaving Python 2 behind in 2017 if the cost exceeds a certain threshold)

**Comment by malinoff** [comment]
> Ohhh…so you implemented it only on a per-attribute basis instead of per-class?

Yes. In my opinion, if we have a per-attribute way of specifying keyword-only attributes making a whole class keyword-only is easy:
```python
from functools import partial
kw_attrib = partial(attr.ib, kw_only=True)
@attr.s
class Foo:
    bar = kw_attrib()
    baz = kw_attrib()
```

But maybe an additional `attr.s` option (`kw_only`) is worth implementing. I don't know, I feel no evil with `partial` approach.

**Comment by malinoff** [comment]
(BTW, I don't understand why codecov report says the coverage decreased. These lines do not seem to correlate with my changes.)

**Comment by malinoff** [comment]
@hynek regarding Python 2 emulation of keyword-only arguments, I've found https://github.com/pasztorpisti/kwonly-args.
Although it works to some extent, it's still doesn't exactly match Python 3 behavior:
```python
Python 2.7.14 (default, Oct  8 2017, 18:34:38)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kwonly_args import first_kwonly_arg, KWONLY_REQUIRED
>>> @first_kwonly_arg('b')
... def foo(a, b=KWONLY_REQUIRED, c=KWONLY_REQUIRED, d=4):
...   pass
...
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/malinoff/Projects/opensource/attrs/venv27/lib/python2.7/site-packages/kwonly_args/__init__.py", line 108, in wrapper
    ', '.join(sorted(missing_kwonly_args))))
TypeError: foo() missing 2 keyword-only argument(s): b, c
>>> foo(1, 2, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/malinoff/Projects/opensource/attrs/venv27/lib/python2.7/site-packages/kwonly_args/__init__.py", line 108, in wrapper
    ', '.join(sorted(missing_kwonly_args))))
TypeError: foo() missing 2 keyword-only argument(s): b, c
```
vs
```
Python 3.6.1 (default, May 29 2017, 09:11:03)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def foo(a, *, b, c, d=4):
...   pass
...
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() missing 1 required positional argument: 'a'
>>> foo(1, 2, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() takes 1 positional argument but 3 were given
```

And the implementation is scary enough for me not wanting to translate it into the [list of lines](https://github.com/python-attrs/attrs/blob/1bb8fbd5ef0ba82265cb993444fe2838477cba4f/src/attr/_make.py#L879) used to generate the `__init__` body. Maybe somebody else has courage to do so.

What do you think about adding this as a Python 3 only feature for now?

**Comment by malinoff** [comment]
Rebased onto master.

**Comment by malinoff** [comment]
@Tinche since you've been pretty active in the referenced issues, I'd like to hear your opinion too.

**Comment by hynek** [comment]
As I’ve said, I don’t mind leaving Python 2 behind if it means too much work.  @Tinche is currently having a life-or-death battle with a manflu, but this won’t make 17.3 anyways, so no pressure. :)

**Comment by leezu** [comment]
@malinoff Implementing the additional `@attr.s` option would be make this work nicely with `@attr.s(auto_attribs=True)`, or am I overlooking something? I.e. it would remove the need for `attr.ib` calls..

Quoting an usage example from the [docs](https://attrs.readthedocs.io/en/stable/examples.html#types)
```
>>> import typing
>>> @attr.s(auto_attribs=True)
... class AutoC:
...     cls_var: typing.ClassVar[int] = 5  # this one is ignored
...     l: typing.List[int] = attr.Factory(list)
...     x: int = 1
...     foo: str = attr.ib(
...          default="every attrib needs a type if auto_attribs=True"
...     )
...     bar: typing.Any = None
```

**Comment by malinoff** [comment]
@leezu having only an `attr.s` option locks you between `def foo(a, b, c=3):` and `def foo(*, a, b, c=3):`.
Having an `attr.ib` option gives you enough flexibility: `def foo(a, *b, c=3):` _and_ allows to implement the corresponding `attr.s` option for short-cut and convenience.

Also, I've opened this PR before 17.3 have been released, so I couldn't take `auto_attribs` into account at that time.

@hynek @Tinche, since 17.3 was cut off, could you please take a closer took at this PR?

**Comment by RonnyPfannschmidt** [comment]
would it be acceptable for python2 support to use a `**kw_somewhat_unreadable_123` name combined with a funcsigs2 signature object that would return the complete signature for correctness ?

(given that popping from the dict + asserting can work, but the signature would suck

**Comment by leezu** [comment]
@malinoff essentially I would like to avoid writing out `attr.ib` for every attribute (based on `auto_attribs=True`), but still be able to use keyword-only arguments. 

>  Having an attr.ib option gives you enough flexibility: def foo(a, *b, c=3): and allows to implement the corresponding attr.s option for short-cut and convenience.

Do you mean the `kw_attrib` partial? It doesn't allow avoiding `attr.ib` (or well, now `kw_attrib`).

You can argue that using keyword-only arguments is an advanced use-case, so it should require the "more complex" `attr.ib` syntax instead of the type hint based syntax with `auto_attribs=True`. I think otherwise, but please let me know if you disagree.

> having only an attr.s option locks you between def foo(a, b, c=3): and def foo(*, a, b, c=3):

What about not "only an attr.s option" but an "shortcut attr.s option" which defaults to `def foo(*, a, b, c=3)` and more complex use-cases can be implemented via the corresponding `attr.ib` calls?

**Comment by malinoff** [comment]
@leezu 
> What about not "only an attr.s option" but an "shortcut attr.s option" which defaults to `def foo(*, a, b, c=3)` and more complex use-cases can be implemented via the corresponding `attr.ib` calls?

That's what I mean in my previous reply.

**Comment by ronlut** [comment]
Sorry for bursting into your conversation, but I hope it's related enough.
Will this PR (or combined with anything else already implemented) allow me to use `attrs` for something similar to this use case:

```
class A:
    def __init__(self, **kwargs):
        for key in kwargs:
            setattr(self, key, kwargs[key])
```

I guess it's more related to your plan to add an option to attr.s and not the attr.ib one.

**Comment by veltzerdoron** [comment]
I see this is not implemented in the code yet, will it be a part of version 17.4?

**Comment by hynek** [comment]
Unlikely, 17.4 is gonna be a mostly (overdue) bug fix release that should drop next week if nothing comes up.

**Comment by alanhdu** [comment]
@malinoff Is there anything else that needs to happen with this PR? I'm happy to take over the branch to try to get it in if you don't have the time).

(Although for my own use-case, I just need the class-level `kw_only` flag, but not the `attr.ib` level flag).

**Comment by asvetlov** [comment]
See also python/cpython#6238

**Comment by malinoff** [comment]
I'm okay to finish the PR by myself, I just don't understand what else should be implemented/fixed.

**Comment by alanhdu** [comment]
@hynek Can you comment on what else needs to happen here (other than the merge conflicts obviously)? Is this blocked on the design issue of the whether this should also be an `attr.s` option?

(FWIW @malinoff I *really* would like the `attr.s` option so this works nicely with `auto_attribs`).

**Comment by alanhdu** [comment]
Sorry to be a bother, but bump @hynek

**Comment by hynek** [comment]
fixed by #411

**Pull request closed without merging**
