### PR TITLE
Add logo in SVG

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by blueyed** [comment]
Is it used automatically?

**Comment by hroncok** [comment]
Used in what way? I only added it in the repo in case anyone finds it useful.

**Comment by hynek** [comment]
Oh dear, did you trace it by hand?  I totally have the source material in different formats (I actually paid for it 🙈) I just didn't know where to put it.

**Comment by hroncok** [comment]
I did it for fun, so no worry :)

**Comment by hynek** [comment]
😅

**Comment by hynek** [comment]
(I have opened #248 to fix this)

**Pull request closed without merging**
