### PR TITLE
Switched from __dataclass_transform__() to typing.dataclass_transform()

### PR DESCRIPTION
**Pull request by superbobry**
# Summary

This PR replaces the non-standard `__dataclass_transform__()` in type stubs with `typing.dataclass_transform()`, introduced in [PEP-681](https://peps.python.org/pep-0681/).

The only difference between the two decorators is the naming of one parameter: `field_descriptors=` in `__dataclass_transform__()` is now `field_specifiers=`.

# Pull Request Check List

- [ ] Added **tests** for changed code.
  Our CI fails if coverage is not 100%.
- [ ] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- [ ] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [ ] ...and used in the stub test file `tests/typing_example.py`.
    - [ ] If they've been added to `attr/__init__.pyi`, they've *also* been re-imported in `attrs/__init__.pyi`.
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
          The next version is the second number in the current release + 1.
          The first number represents the current year.
          So if the current version on PyPI is 22.2.0, the next version is gonna be 22.3.0.
          If the next version is the first in the new year, it'll be 23.1.0.
- [ ] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/main/changelog.d).
- [ ] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

### CODE REVIEW

**Comment by hynek** [comment]
I'll leave the review to our resident typing czar but [please add a news fragment](https://github.com/python-attrs/attrs/blob/main/.github/CONTRIBUTING.md#changelog).

**Comment by hynek** [comment]
Tiiin, it's greeeeeen!

**Comment by Tinche** [comment]
I'll install this branch into a bunch of our codebases and see if it's gucci.

**Comment by Tinche** [comment]
Seems to work!

**Review by Tinche — APPROVED** [review]

**Pull request merged**
