### PR TITLE
Use the stable version of Python 3.11 in CI

### PR DESCRIPTION
**Pull request by l1storez**
This patch updates the use of Python 3.11 in CI to the newly released stable version, in the test jobs. It also moves the non-test jobs from Python 3.10 to 3.11

### CODE REVIEW

**Review by webknjaz — APPROVED** [review]
@hynek mind allowing the CI to run?

**Comment by l1storez** [comment]
@webknjaz please help

**Comment by webknjaz** [comment]
@l1storez `step-security/harden-runner` action blocks the ability of `actions/setup-python` to download Python 3.11. You'll need to adjust the `allowed-endpoints` value for the failing jobs to allow this, like this is done in the passing jobs.

**Comment by l1storez** [comment]
okay, I will fix it

**Comment by varunsh-coder** [comment]
@l1storez please let me know if you need any help with adjusting the allowed endpoints. Based on the insights [here](https://github.com/python-attrs/attrs/actions/runs/3350788753/jobs/5551865071#step:2:19), looks like calls to `api.github.com:443` are being blocked in the jobs that are failing.

**Comment by l1storez** [comment]
add `api.github.com:443` to jobs, need a test run of workflow to check if changing was right

**Comment by webknjaz** [comment]
@hynek allow the CI plz

**Comment by l1storez** [comment]
smth goes wrong. Checks passed. I'll squash the commits locally and push

**Review by hynek — APPROVED** [review]
Thanks!

**Pull request merged**
