### PR TITLE
Suppress HealthCheck.too_slow for TestAsTuple.test_recurse_property

### PR DESCRIPTION
**Pull request by floppym**
On very slow hardware, this test fails due to a hypothesis health check.

Bug: https://bugs.gentoo.org/show_bug.cgi?id=608570

### CODE REVIEW

**Comment by hynek** [comment]
That suppresses the health check only on the one test, right?  Wouldn’t it be better to allow to suppress them completely for such cases?  Summoning @Tinche :)

**Comment by Tinche** [comment]
Sure. @floppym, could you suppress the slow warning on all test cases that make use of nested_classes?

**Comment by floppym** [comment]
@Tinche Maybe I'm missing something, but this is the only test I see that references `nested_classes`.

**Comment by Tinche** [comment]
@floppym TestAsDict.test_recurse_property, TestAsTuple.test_recurse_property, TestAsTuple.test_recurse_retain :)

**Comment by floppym** [comment]
Oh, duh. I force pushed a new changeset.

**Comment by hynek** [comment]
Did the org transition break CodeCov? 😭

**Comment by hynek** [comment]
Thank you for your contribution!

**Pull request merged**
