### PR TITLE
Add default_role for Sphinx.

### PR DESCRIPTION
**Pull request by Julian**
(Mentioned in https://github.com/python-attrs/attrs/pull/568#discussion_r321687907)

Fix a bunch of broken refs along the way, which become
errors now via -W if you have default_role set.

In theory you can catch those via sphinx-build -n (i.e.
nitpick mode), which IMHO is a decent idea anyhow, but it's
a longer diff to enable that because it'd involve fixing a
bunch of the places that try to reference types that don't
exist (e.g. :type foo: Any value). But obviously can be done.

Also didn't actually use this anywhere yet (the any role),
but will do so in a follow-up if this is acceptable.

But throwing the PR up as-is just to show what I meant / see if it's something we want.

# Pull Request Check List

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] Added **tests** for changed code.
- [x] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/strategies.py).
- [x] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [x] ...and used in the stub test file `tests/typing_example.py`.
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
- [x] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/master/changelog.d).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by Julian** [comment]
OK and now I just used this for a bunch of builtin refs just to show you how it looks. I can keep going, but actually there are some more broken refs hiding that don't become errors without `nitpick`. E.g.: https://github.com/python-attrs/attrs/blob/f84f451557bd816b1ba525d98a431709449fdf1e/src/attr/validators.py#L207 this is actually a broken ref (to `NotCallableError`), which doesn't seem like it's included in any document, but that doesn't raise an error without having nitpick mode turned on unless you try to `any`-role-ref it.

**Comment by hynek** [comment]
That looks cool overall. If we go that way it should definitely pass in nitpick mode if it's possible at all.

**Comment by Julian** [comment]
OK done. And looks like there weren't very many more broken references after the first few, so that's good, was fairly easy.

So nitpick mode is enabled -- I use the most "conservative" way to handle non-types being mentioned as types myself -- which is basically from now on you literally need to whitelist those in Sphinx's config. IMO this is the right idea considering just how easy it is to get Sphinx to silently not link a reference (as you saw without -n :/) but there are some other ways to do this if you don't like this one.

(Sphinx *will* though error if the default_role finds multiple possible targets, so if you accidentally have a doc and a type named the same thing or whatever, you're still fine in that you'll get a non-silent failure.)

**Comment by hynek** [comment]
Cool, TIL, thanks!

**Pull request merged**
