### PR TITLE
Implement attr.converters.default_if_none

### PR DESCRIPTION
**Pull request by hynek**
So this is a stab at #400 which I find a reasonable usage of converters.

Typing tests fail tho and they also fail for `attr.validators.optional`. Am I right to suspect that this has to be fixed in mypy's plugin? Gives us a bit of a Mexican stand-off, doesn't it? It’s completely possible that I additionally got the stubs wrong so feel free to advice.

cc @euresti @chadrik

### CODE REVIEW

**Comment by euresti** [comment]
Yeah this is something the plugin currently doesn't support:

`error: Unsupported converter, only named functions and types are currently supported`

The underlying problem is that it's hard to extract the type of the function call in the mypy pipeline.

A workaround could be to write:
```
optional_int = optional(int)

@attr.s
class ConvCOptional:
    x: Optional[int] = attr.ib(converter=optional_int)
```

But that's broken also, but I think easier to fix.  Now I remember, in our work code, when we started using mypy I removed all our uses of optional and just wrote our own converters.

**Comment by hynek** [comment]
I guess until mypy opens up it's plugin API (I talked to Jukka here at EuroPython and it's legit on their roadmap) we’ll have to comment stuff out, wait for mypy to release the support? Having hard-coded support is “fine” for now…

***

Does the signature look correct to you tho? If someone rubber-stamps it, I’ll just comment it out and we open an issue on mypy.

**Comment by euresti** [comment]
I can review the signature.  As for commenting it out I'm not sure since I'm not sure when we'll fix the plugin.  It might be a while.

**Comment by hynek** [comment]
Just to be clear: by special casing I mean that mypy only supports our shipped converters for now. Would that be a significant amount of work too?

**Comment by euresti** [comment]
Hmm.  Maybe I could detect the converters by name and handle them specially.  That might actually work.

**Comment by hynek** [comment]
> Hmm. Maybe I could detect the converters by name and handle them specially. That might actually work.

Yeah, that’s what I was thinking.

**Comment by euresti** [comment]
FYI: https://github.com/python/mypy/pull/5411   Here's one implementing `optional`, we'll see what the mypy folks say.

**Pull request merged**
