### PR TITLE
📦 Enable support for git archive installs

### PR DESCRIPTION
**Pull request by webknjaz**
# Summary

This patch enables the end-users to succeed installing from GitHub source Git archive URLs, letting `setuptools-scm` calculate the distribution version correctly, including the exports of non-tagged commits [[1]].

[1]: https://github.com/pypa/setuptools_scm#git-archives

# Pull Request Check List

- [x] Added **tests** for changed code.
  Our CI fails if coverage is not 100%.
- [x] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- [x] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [x] ...and used in the stub test file `tests/typing_example.py`.
    - [x] If they've been added to `attr/__init__.pyi`, they've *also* been re-imported in `attrs/__init__.pyi`.
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
          The next version is the second number in the current release + 1.
          So if the current version on PyPI is 23.1.0, the next version is gonna be 23.2.0.
- [x] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/main/changelog.d).
- [x] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

### CODE REVIEW

**Comment by webknjaz** [comment]
Proof that this works:
```console
$ pip install https://github.com/webknjaz/attrs/archive/maintenance/packaging-git-archives-support.tar.gz
Collecting https://github.com/webknjaz/attrs/archive/maintenance/packaging-git-archives-support.tar.gz
  Downloading https://github.com/webknjaz/attrs/archive/maintenance/packaging-git-archives-support.tar.gz
     \ 208 kB 750 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: attrs
  Building wheel for attrs (PEP 517) ... done
  Created wheel for attrs: filename=attrs-22.1.1.dev156-py3-none-any.whl size=59959 sha256=5fca3d4e94fdbd7dc5515da4b6e45c69db01a1fae3bb16aac1b168f5570f61d9
  Stored in directory: ~/.cache/pip/wheels/29/55/36/3b514229ffa36f05afab77610f4e90f30f1f595a2fb5aba2a9
Successfully built attrs
Installing collected packages: attrs
Successfully installed attrs-22.1.1.dev156
```

**Review by hynek — APPROVED** [review]
cool thanks! I guess I'll have to look at my other projects too!

**Comment by hynek** [comment]
@webknjaz I have just noticed two new warnings while building:

```
/tmp/build-env-c8w_zcyy/lib/python3.10/site-packages/setuptools_scm/git.py:295: UserWarning: git archive did not support describe output
[125](https://github.com/python-attrs/attrs/actions/runs/4101911014/jobs/7074233132#step:5:131)
  warnings.warn("git archive did not support describe output")
[126](https://github.com/python-attrs/attrs/actions/runs/4101911014/jobs/7074233132#step:5:132)
/tmp/build-env-c8w_zcyy/lib/python3.10/site-packages/setuptools_scm/git.py:312: UserWarning: unexported git archival found
[127](https://github.com/python-attrs/attrs/actions/runs/4101911014/jobs/7074233132#step:5:133)
  warnings.warn("unexported git archival found")
```

What exactly do they mean? Can we fix them or do we have to ignore them? I'm getting them locally too, that's how I noticed.

**Comment by webknjaz** [comment]
I only looked at the logs from phone and it seems to be happening during sdist creation. The warning seems to indicate an old Git version so I'd update it first thing, maybe that's enough.

**Comment by RonnyPfannschmidt** [comment]
im pretty sure this can happen when creating a sdist while the file finder is active
a manifest exclude for the .git_archival should help to keep the un-evaluated archival off the hands of setuptools_scm

**Comment by webknjaz** [comment]
@RonnyPfannschmidt are you implying that the behavior that hatch/hatch-vcs has might differ from setuptools, in how this is included in sdist?

**Comment by RonnyPfannschmidt** [comment]
I missed the hatch migration, for hatch the exclude location differs from

**Comment by webknjaz** [comment]
@RonnyPfannschmidt is the expectation that this is just excluded?

**Comment by RonnyPfannschmidt** [comment]
No, the detail issue is that the bugfix for missed archival was tested in isolation and we missed that it warns for correct sdists depending on the order of entrypoints

**Comment by webknjaz** [comment]
Ah, so no changes are needed here.

**Comment by hynek** [comment]
Wait, I didn't understand any of this. 😅 What's happening?

**Comment by webknjaz** [comment]
@hynek: @RonnyPfannschmidt said that it's a bug in the setuptools-scm upstream so we just need to wait for the fix.

**Comment by hynek** [comment]
OK but the bug is the warning – the packages are OK, right?

**Comment by RonnyPfannschmidt** [comment]
Correct

**Pull request merged**
