### PR TITLE
warn when combining types as converter and None as default -  #385

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
# Pull Request Check List

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](http://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [ ] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/strategies.py).
- [x] Updated **documentation** for changed code.
- [x] Documentation in `.rst` files is written using [semantic newlines](http://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
- [x] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/master/changelog.d).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by hynek** [comment]
So I’m not comfortable to merge this because we can't make any assumptions about what a type that is `is class(t) is True` takes or not. It might be completely purposeful and we would just spam warnings at users.

How about a doc change?

**Comment by RonnyPfannschmidt** [comment]
from what i can tell - its practically always a mistake to have a non-factory default when using a type as converter

consider `attr.ib(default=None, converter=int)` vs `attr.ib(factory=int, converter=int)`

**Comment by hynek** [comment]
Yes but what if converter is not an int but a class that can handle a None just fine? That’s different from something being optional.

**Comment by RonnyPfannschmidt** [comment]
@hynek i argue that in that case a factory use is still the better api as it removes the None as magical value

the pr as i present it removes the usage of `None` as a magical pass trough value to ensure "correct" operation

imho this makes the intents much more clear - and its totally fine to warn on it

ideally there would be a concept to unify converter/factory but im not aware of something that fits the bill

**Comment by hynek** [comment]
To be clear, I’m not saying you’re wrong.

I’m just not sure we can introduce a warning willy-nilly when people may have code like this:

```python
@attr.s
class C:
    x = attr.ib()

@attr.s
class D:
    c = attr.ib(default=None, converter=C)
```

So C is a wrapper for whatever is passed as a value for c and None is a perfectly valid value – you always want a valid c tho: `D(c=C(x=None))`. What would be your workaround? Since converters are called on defaults (in hindsight, this seems like a big design mistake), I don’t see a better way.

You wrote that one needs a None-aware `__init__` but AFAICT, there’s no good way to detect whether one is.

I’d welcome opinions of others on this topic. 🤔

**Comment by RonnyPfannschmidt** [comment]
@hynek to make my point the example you posted is broken

```
>>> D(C(1)), D(1)
(D(c=C(x=C(x=1))), D(c=C(x=1)))
```

**Comment by hynek** [comment]
I’m a bit lost here, why is it broken? Converters are always run unconditionally so it does exactly what I'd expect?

**Comment by RonnyPfannschmidt** [comment]
@hynek but think user perspective - the instance is wrapped instead of coerced - i'm certain that the use you posted is unintended and unwanted in almost all cases

**Comment by hynek** [comment]
Yes, it’s weird…but what has it to do with the subject matter of this ticket? I feel super dense. All I see, is that converter is not great in many cases but I don’t see how any of that is fixed with the current patch?

**Comment by RonnyPfannschmidt** [comment]
@hynek this patch is to make one of the vectors where its very very likely to just completely misuse it easily user-visible

**Comment by RonnyPfannschmidt** [comment]
right now it is just really really easy to silently get things wrong/unintended - and even miss the details of that because "now attrs solves that problem"

**Comment by RonnyPfannschmidt** [comment]
closing as loose end

**Pull request closed without merging**
