### PR TITLE
Fix unbound __str__ on Python 2 when slots=True

### LINKED ISSUE #198: slots=True is incompatible with str=True
`slots=True` seems to be incompatible with `str=True`. I discovered this using attrs for exceptions, but it seems true in general:

```pycon
>>> import attr
>>> @attr.s(str=True, slots=True)
... class Foo(object):
...     x = attr.ib()
...
>>> f = Foo(1)
>>> str(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unbound method repr_() must be called with Foo instance as first argument (got nothing instead)
```

Python 2.7.13, attrs==17.2.0

### PR DESCRIPTION
**Pull request by rouge8**
Previously:

```pycon
>>> import attr
>>> @attr.s(str=True, slots=True)
... class A(object):
...     a = attr.ib()
...
>>> a = A(1)
>>> str(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unbound method repr_() must be called with A instance as first argument (got nothing instead)
```

Fixes #198.

# Pull Request Check List

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](http://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [x] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/utils.py).
- [ ] Updated **documentation** for changed code.
- [x] Documentation in `.rst` files is written using [semantic newlines](http://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
- [x] Changes (and possible deprecations) are documented in [`CHANGELOG.rst`](https://github.com/python-attrs/attrs/blob/master/CHANGELOG.rst).

### CODE REVIEW

**Comment by rouge8** [comment]
Blergh, build failed on `tox -e flake8` because of https://github.com/pypa/setuptools/issues/1042

**Comment by hynek** [comment]
trying to fix in #200

**Comment by hynek** [comment]
OK now I was *super* confused why GitHub was claiming, that the branch is up to date. 😅

**Comment by rouge8** [comment]
I beat you to the update 😉

**Comment by hynek** [comment]
Thanks!

**Pull request merged**
