### PR TITLE
Fix cell rewriting some more.

### PR DESCRIPTION
**Pull request by Tinche**
Don't ask.

(Actually you can ask, hope the comments are enough.)

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
by now it begs the question whats wrong with just using a metaclass, they would avoid all the rewriting and ensure subclasses will always be handled correctly

**Comment by hynek** [comment]
Just arrived home, flake8 fails, good night. :)

**Comment by Tinche** [comment]
Welcome home!

*cough* In my defense, the code works, it's a pyflakes bug. *cough*

**Comment by hynek** [comment]
Could you add the test case from #269 to test_dark_magic too please?

**Comment by hynek** [comment]
> by now it begs the question whats wrong with just using a metaclass, they would avoid all the rewriting and ensure subclasses will always be handled correctly

Maybe, but it also adds a bunch of unknown unknowns. :|  It’s hard to know what obscure edge cases we break by that.

**Comment by Tinche** [comment]
I'll add the test when I get some time, it's no problem.

**Comment by Tinche** [comment]
I see you've already added it 💋

**Pull request merged**
