### PR TITLE
Add a testtools matcher-based validator.

### PR DESCRIPTION
**Pull request by exarkun**
Fixes https://github.com/hynek/attrs/issues/13

### CODE REVIEW

**Comment by hynek** [comment]
Hm it certainly intriguing to pass on this kind functionality to someone who considers on of their core features.

But is this something people actually *do*?  Use testtools in normal code?

**Comment by exarkun** [comment]
What happened to https://github.com/hynek/attrs/issues/13#issuecomment-113104985 which seemed to be explicit approval of this feature?

No, I've never done this before - but I contributed this upstream so I *could* do it with an official attrs API instead of carrying the implementation in my random no-one-will-ever-look-at-it codebase.  I started with a custom, attrs-only implementation of a testtools AllMatches-alike and was quite happy to be able to throw it away and use someone else's code (and at the same time open up many other combining operators).

**Comment by exarkun** [comment]
@hynek ping

**Comment by hynek** [comment]
What happened?  Dementia happened. :D 

So I’m cool with adding a testtools-based matcher if enough people think it’s a good idea and they would use it (@cyli? @glyph? @PsyMar?) but I’m not entirely happy with name that makes it look like it’s self-implemented.  `testtools_matches()` OTOH seems a bit of mouthful?  Opinions?

**Comment by PsyMar** [comment]
Hm, never encountered testtools before (I only started python last year, don't blame me).  It says it derives from unittest, which never looked particularly helpful, but maybe that's just because of the examples I've seen.  I'll look through those docs...

as for a name, I don't mind long names, but I switched to Python from Java (and previously C++ which the boost libraries are AWFUL about long names.)

**Comment by hynek** [comment]
I’m sorry but I’m going to close this now.  Thinking about it, testtools seems like a poor choice to use as the official validation vehicle.

I think I’d rather add something like https://github.com/alecthomas/voluptuous which is more generic and production tested (by myself no less :)).

Sorry for the work jp! :(

**Comment by exarkun** [comment]
Meh :/

**Pull request closed without merging**
