### PR TITLE
Preserve metaclass when slots=True

### LINKED ISSUE #154: Metaclass lost with slots=True
Hello.

Using a metaclass with slots=True, e.g.
```
@attr.s(slots=True)
class A(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def f(self):
        pass
```
Will lead to `A` being instantiable and `type(A)` being `<class 'type'>` (unlike the case with slots=False), as for slots to work the new class is generated in [_make.py](https://github.com/python-attrs/attrs/blob/master/src/attr/_make.py#L365) with:

`cls = type(cls.__name__, cls.__bases__, cls_dict)` [1]

This doesn't happen if this line is changed to:

`cls = type(cls)(cls.__name__, cls.__bases__, cls_dict)` [2]

With this change `type(A)` is `<class 'abc.ABCMeta'>` and A is no longer instantiable.
Can the class generation for slots be changed to something like [2] to avoid losing metaclasses or it is intentionally written as it is now and I am missing something?

### PR DESCRIPTION
**Pull request by YevIgn**
Fixes #154

### CODE REVIEW

**Comment by hynek** [comment]
fyi the tests fail on py2/pypy2

**Comment by YevIgn** [comment]
Sorry, doubt I can fix the new test, without bringing analog of `six.add_metaclass` to the code, or using an ugly hack with `eval`.

**Comment by Tinche** [comment]
Hm. Can we bring in six as a test dependency?

**Comment by hynek** [comment]
I don’t mind.  I don't want runtime deps to check for PY3 but reimplementing metaclass magic just for tests seems like a bridge too far.

**Comment by hynek** [comment]
Tin please take this; I have willfully forgotten everything I ever knew about meta classes.

**Comment by Tinche** [comment]
Sure thing. I'm sick atm though so it'll have to wait a little

**Comment by hynek** [comment]
Get well soon!

**Comment by hynek** [comment]
I’ve updated the branch and it passes now.

Thanks for the input and I hope you feel better!

**Pull request merged**
