### PR TITLE
Add documentation about string annotations

### PR DESCRIPTION
**Pull request by euresti**
# Pull Request Check List

This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.

- [x] Added **tests** for changed code.
- [x] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/strategies.py).
- [x] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [x] ...and used in the stub test file `tests/typing_example.py`.
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in our [``__init__.py``](https://github.com/python-attrs/attrs/blob/master/src/attr/__init__.py) file.
- [x] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/master/changelog.d).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by euresti** [comment]
I'm not the best at writing documentation so please review strongly.  :)

**Comment by hynek** [comment]
Thanks, I'm gonna massage it into shape myself (*cough* semantic newlines *cough*)!

One question tho and I realize that this has been discussed but I guess that should be part of this:

Is there anything preventing us to give our users tools to resolve these references for them (recursively)? I.e. `attr.resolve_all_types(SomeAttrsClass)` will walk all attributes and replace the string literals if it can?

**Comment by euresti** [comment]
We could bring back #302.  Back then we sort of decided that if you needed the real types you should probably use `get_type_hints`.  But maybe we're getting more requests for `type=` to be meaningful.

**Comment by hynek** [comment]
Yeah people keep asking and if we can make it recursive, that would save work. Unless we can side-step the whole thing with what you mentioned in https://github.com/python-attrs/attrs/issues/593#issuecomment-657578711?

**Comment by euresti** [comment]
My comment in #593 is only about calling `get_type_hints(C.__init__)`  Calling `get_type_hints(C)`should work because it looks up the globals in the class module.

**Comment by hynek** [comment]
Oof OK sorry!

So how about:

1. we bring back #302 and get it merged
2. amend this PR and merge it?

**Comment by hynek** [comment]
Yay, step 1 is done! Can I bother you to amend the docs with `attr.resolve_types()`? 🥺

**Comment by euresti** [comment]
Text has been updated. Feel free to edit or send comments!

**Comment by euresti** [comment]
Ugg.  My `git commit` didn't work.  Hang on.

**Comment by euresti** [comment]
All right.  Let me know what you think.  I had a section about how it usually can't be done at "class creation time" but I decided to remove it.

**Comment by hynek** [comment]
thanks!

**Pull request merged**
