### PR TITLE
Inline distutils.util.strtobool in tests (closes #813)

### LINKED ISSUE #813: Python 3.10 deprecation in tests due to distutils
The function is simple enough to be vendored for tests.

```
tests/test_converters.py:7
  /root/checked_repos/attrs/tests/test_converters.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.util import strtobool

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

https://github.com/python-attrs/attrs/blob/d0cff8face92478c950ba05a7d9403b1e342407a/tests/test_converters.py#L7

### PR DESCRIPTION
**Pull request by 9999years**
`distutils` is deprecated in Python 3.10 and slated for removal in Python 3.12. Fortunately, `attrs` only uses `distutils` once and it's trivial to remove.

As suggested by @sscherfke, add the `to_bool` converter to `converters.py`.

Closes #813

# Pull Request Check List

This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.  If your pull request is a documentation fix or a trivial typo, feel free to delete the whole thing.

- [x] Added **tests** for changed code.
- [x] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- [x] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [x] ...and used in the stub test file `tests/typing_example.py`.
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in our [``__init__.py``](https://github.com/python-attrs/attrs/blob/main/src/attr/__init__.py) file.
- [x] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/main/changelog.d).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by sscherfke** [comment]
Hi Rebecca, thanks for your PR. I am already working on this issue in #824 though (the PR title may be a little bit mesleading). 

I think we should combine our efforts there. :)

**Comment by 9999years** [comment]
Alright -- do you need any support from me? Feel free to move my work to your branch.

**Comment by sscherfke** [comment]
Maybe (just maybe) we should keep it simple and prefer your PR over mine. 

I think @Tinche would agree that conversion should be done with cattrs anyways, so why add a lot of converters to attrs? On the other hand, they don't hurt and may be very handy for some use cases. I’ll have to think about this and discuss it with him and Hynek. :)

**Comment by hynek** [comment]
Yeah we can do this separately!

However, we're gonna need to make this pass on 2.7 and 3.5 too. 😇

**Comment by hynek** [comment]
And now we need two tests to fix coverage. 😇

**Comment by 9999years** [comment]
OK, got those tests in!

**Review by hynek — APPROVED** [review]
Thanks!

**Pull request merged**
