### PR TITLE
Opt into uploading PEP 740 digital publish attestations to PyPI

### PR DESCRIPTION
**Pull request by webknjaz**
# Summary

This patch enables the release workflow to sign the artifacts digitally and attach said signatures to PyPI releases: https://github.com/pypa/gh-action-pypi-publish/pull/236

### CODE REVIEW

**Review by hynek — APPROVED** [review]
🎉

**Comment by hynek** [comment]
this doesn't work:

```
Checking dist/attrs-24.2.1.dev14-py3-none-any.whl: PASSED
Checking dist/attrs-24.2.1.dev14.tar.gz: PASSED
Notice: Generating and uploading digital attestations
Error: Attestation generation failure: The following paths look like distributions but are not actually files: /github/workspace/dist/attrs-24.2.1.dev14.tar.gz, /github/workspace/dist/attrs-24.2.1.dev14-py3-none-any.whl
```

**Comment by hynek** [comment]
I've restored the branch for the next attempts… the error is rather mysterious, maybe @woodruffw has an idea?

https://github.com/python-attrs/attrs/actions/runs/10676826709/job/29591009736#step:4:17

**Comment by webknjaz** [comment]
Oh no.. Perhaps, that check needs to be inverted.

**Comment by webknjaz** [comment]
@hynek it's fixed now!

**Comment by hynek** [comment]
Yay! I see no difference on PyPI?

**Review by Yedfree — APPROVED** [review]

**Pull request merged**
