### PR TITLE
WIP: Allow evolve() to recursively evolve attrs classes

### LINKED ISSUE #634: Recursive attr.evolve
In the same manner as `attr.asdict(..., recursive=True)` exists, I have a use case for a similar option to `attr.evolve()`. I want all attr instances evolved, but with no need to deepcopy any non-attr attributes. I ended up implementing the code below. Could this be a consideration for addition into `python-attrs`?

```python
def evolve_recursive(inst, **changes):
    """ Recursive attr.evolve() method, where any attr-based attributes
        will be evolved too.
    """
    cls = inst.__class__
    attrs = attr.fields(cls)
    for a in attrs:
        if not a.init:
            continue
        attr_name = a.name  # To deal with private attributes.
        init_name = attr_name if attr_name[0] != "_" else attr_name[1:]
        if init_name not in changes:
            value = getattr(inst, attr_name)

            # New code
            if attr.has(value.__class__):
                value = evolve_recursive(value)

            changes[init_name] = value
    return cls(**changes)
```

### PR DESCRIPTION
**Pull request by sscherfke**
This is a new atempt to fix #634 (#759 failed: #804, #806)

# Pull Request Check List

This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.  If your pull request is a documentation fix or a trivial typo, feel free to delete the whole thing.

- [x] Added **tests** for changed code.
- [x] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- [x] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [x] ...and used in the stub test file `tests/typing_example.py`.
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in our [``__init__.py``](https://github.com/python-attrs/attrs/blob/main/src/attr/__init__.py) file.
- [x] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/main/changelog.d).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by sscherfke** [comment]
Oh, Pyhton 2! 😿

**Comment by sscherfke** [comment]
What do you think, @hynek?  Time for another try?

This time, recursive evolving works a bit more defensively – only if an attribute explicitly annotates a type.  And we have a few more tests.  I’m not sure though if this is enough. 🤷

**Comment by hynek** [comment]
This probably doesn't work with string type annotations?

My gut feeling is that it's too much magic and too many sharp edges. I wonder if we introduced a new API, how this case could be made water-proof?

**Comment by sscherfke** [comment]
Yes, stringy type annotations do break, of course.

I’ll play around with it in typed settings for a while.  It would be very useful there for monkeypatching nested frozen settings classes in tests.

**Comment by jacobg** [comment]
The following unit test fails. Not sure if your intent was to support settings sparse values.

```python
def test_evolve_recursive_deep():

    @attr.s(auto_attribs=True, frozen=True, slots=True)
    class Baz:
        a: str
        b: str

    @attr.s(auto_attribs=True, frozen=True, slots=True)
    class Bar:
        baz: Baz

    @attr.s(auto_attribs=True, frozen=True, slots=True)
    class Foo:
        bar: Bar

    foo = Foo(bar=Bar(baz=Baz(a='a1', b='b1')))

    assert evolve_recursive(foo, bar={'baz': {'a': 'a2'}}) ==\
           Foo(bar=Bar(baz=Baz(a='a2', b='b1')))

```

**Comment by hynek** [comment]
Closing for staleness; feel free to open a new one.

**Pull request closed without merging**
