### PR TITLE
Unpin tox

### PR DESCRIPTION
**Pull request by hynek**
It works locally for me.

### CODE REVIEW

**Comment by hynek** [comment]
no it doesn't

**Comment by webknjaz** [comment]
Wait, if it works locally but not in GHA, maybe it's the plugin's fault? I think I've seen a corresponding plugin for tox4 being separate from the one for tox3.

**Comment by hynek** [comment]
no, I ran `tox -e mypy` locally but the broken thing is the test suite. I've isolated & opened a bug: https://github.com/tox-dev/tox/issues/2904

**Comment by webknjaz** [comment]
Ah, I see. But FTR there's https://github.com/tox-dev/tox-gh too.

**Comment by hynek** [comment]
What does that to do with anything? Our problem is that the package pins for Mypy are from PyPI instead of from the local package. I don't see how the plugins play into that.

**Comment by webknjaz** [comment]
It's unrelated to the mypy problem but is related to the tox4 migration, IIUC.

**Comment by hynek** [comment]
> It's unrelated to the mypy problem but is related to the tox4 migration, IIUC.

According to https://pypi.org/project/tox-gh-actions/, tox-gh-actions>=3 works with tox 3 just fine.

I would switch if there's any upsides, but I can't see any rn?

---

Anyways, tox [has fixed the bug](https://github.com/tox-dev/tox/pull/2905) 🎉 and we're waiting for a release now.

**Comment by webknjaz** [comment]
> According to https://pypi.org/project/tox-gh-actions/, tox-gh-actions>=3 works with tox 3 just fine.

Looks like it's `~= 3.0` though.

**Comment by webknjaz** [comment]
FWIW here's some notes regarding the differences https://github.com/tox-dev/tox-gh/issues/7#issuecomment-1013651022

**Comment by hynek** [comment]
what the flying fuck is going on now… it works perfectly fine on my machine!?

**Comment by webknjaz** [comment]
Looks related to the recent Hatch-scm integration. At least one of the logs failed on `int('dev2')`.
Also, I saw a resource warning so there might be an unclosed file descriptor somewhere.

**Comment by hynek** [comment]
but but but… it used to work! otherwise i wouldn’t have merged it! :(

I’m currently in the process of setting up a new computer, once I’m fully functional I’ll look closer *sigh*

**Comment by webknjaz** [comment]
FWIW I checked this branch locally and it does work. Maybe somebody needs to stick https://github.com/marketplace/actions/debugging-with-tmate there and inspect the worker over SSH.

Oh, and I just remembered the most typical setuptools-scm mistake — the contributors usually have a full Git clone locally but CIs tend to do shallow clones. The fix is usually to set the fetch depth to 0 or run git unshallow.

Though, maybe this is not the only problem here, I haven't had time to dig deeper.

**Comment by hynek** [comment]
https://github.com/python-attrs/attrs/pull/1093/commits/0c9b54c887ad117a2c31a91bbbf65341e11a3131 #genius

**Comment by hynek** [comment]
FTR on tox-gh: it seems like it has a very different way of working than tax-gh-actions. I tries using it with structlog and `3.11 = py311` means literally "only run py311" while `tox-gh-actions` essentially says `-f py311`. For attrs it doesn't matter for now, but that's a very significant different:

CleanShot 2023-02-02 at 08 16 50@2x

(using screenshot b/c logs get lost over time)

**Pull request merged**
