### PR TITLE
Update Mypy tests for new Mypy output

### PR DESCRIPTION
**Pull request by Tinche**

### CODE REVIEW

**Comment by Tinche** [comment]
@hynek Think we can merge this now?

**Comment by hynek** [comment]
After the 3.6 one

**Comment by hynek** [comment]
this gives us a conflict now because there's no setup.py anymore 🤓

**Comment by Tinche** [comment]
@hynek Any idea why tox keeps installing an old version of Mypy?

**Comment by peterschutt** [comment]
Hi @Tinche, is it likely due to this?

https://github.com/python-attrs/attrs/blob/46053d703d99a6e7419fd291cbf546340690d69d/pyproject.toml#L45-L47

**Comment by Tinche** [comment]
Yeah, it should be getting the new version, but it isn't for some reason.

**Comment by peterschutt** [comment]
It really looks like tox is installing the tests extras from PyPI.

Tox runs [this line](https://github.com/python-attrs/attrs/actions/runs/3929661107/jobs/6718738075#step:7:35) in the setup:

`python -m pip install --no-compile 'attrs[tests]' 'coverage>=5.3' 'importlib_metadata; python_version < "3.8"'`

To test it out I changed the tox env to:

```ini
[testenv:py3{7,10,11}]
extras = cov
# Python 3.6+ has a number of compile-time warnings on invalid string escapes.
# PYTHONWARNINGS=d and --no-compile below make them visible during the Tox run.
install_command = python -m pip install --no-compile {opts} {packages}
setenv =
    HATCH_BUILD_HOOK_ENABLE_AUTORUN=1
    COVERAGE_PROCESS_START={toxinidir}/pyproject.toml
    PYTHONWARNINGS=d
commands =
    python -m pip install .[tests]  # <================================= added this
    coverage run -m pytest {posargs:-n auto}
```

and got `1338 passed, 9 skipped, 1 xfailed in 28.35s`

**Comment by webknjaz** [comment]
Per my observations, tox4 is not ready to be deployed everywhere blindly. I've had to keep it below v4 in a number of envs and will be evaluating removing the upper bound on the case by case basis, paying close attention at the bugs being fixed meanwhile...

**Comment by webknjaz** [comment]
Per my observations, tox4 is not ready to be deployed everywhere blindly. I've had to keep it below v4 in a number of envs and will be evaluating removing the upper bound on the case by case basis, paying close attention at the bugs being fixed meanwhile...

**Comment by hynek** [comment]
weird… wann try pinning 'tox<4' in ci Tin?

**Comment by Tinche** [comment]
Cool, that fixed it.

Do we want to let Tox maintainers know?

**Comment by hynek** [comment]
> Cool, that fixed it.
> 
> Do we want to let Tox maintainers know?

yeah let's be good citizens

**Review by hynek — APPROVED** [review]
thanks!

**Pull request merged**
