### PR TITLE
Fix MRO traversal with multiple inheritance

### LINKED ISSUE #298: order of attributes is 'backwards' in case of multiple inheritance
consider following code.  I also added a dummy method `m` to show that precedence is "correct"ly follows for a basic method

```python
from attr import attributes, attr

@attributes
class A(object):
    a = attr()
    def m(self):
        print("A.m")

@attributes
class B(object):
    b = attr()
    def m(self):
        print("B.m")

@attributes
class C(A, B):
    c = attr()

    def m(self):
        super(C, self).m()

    @classmethod
    def supers(cls):
        return cls.__bases__

c = C(1, 2, 3)

print(c)
c.m()
print("supers=%s" % str(c.supers()))
```
running it results in 
```
C(b=1, a=2, c=3)
A.m
supers=(<class '__main__.A'>, <class '__main__.B'>)
```
so the first argument is (IMHO) incorrectly assigned to attribute b not a, and then 2nd one to a...

Before recent 3040bdabbc627fc6a4d151a9cb2e6f9d4177b6f2  quick and dirty (and possibly incomplete) fix was to remove `reversed` around mro within src/attr/_make.py  but neither I have looked yet into how logic should be adjusted in the current state of affairs, nor I analyzed for why reversed was needed to start with

### PR DESCRIPTION
**Pull request by hynek**
So the double reversal we used to do screwed up the MRO traversal for forever (i.e. this is not a 17.3 regression, I had to fix examples.rst!).

This fixes it – the question is how we go about it.  A proper deprecation cycle seems impossible again, so I guess we can push it and ask for forgiveness?

This fixes #298 and #299 cc @yarikoptic

### CODE REVIEW

**Comment by yarikoptic** [comment]
Well, +1 from me ;-)

**Comment by hynek** [comment]
Paging @glyph for wise opinions. :|

**Comment by glyph** [comment]
Somewhat belatedly (although it appears in time for a release?) I did have an idea about this.

The deprecation cycle here *could* go like this:

- X.Y emit a warning when calling multiply-inherited `__init__` with positional arguments
- X.Y+1 raise an error when calling multiply-inherited `__init__` with positional arguments
- X.Y+2 add back this positional ordering.

Alternately, if we just want to bite the bullet, we could switch to this behavior, but still emit a warning for a release or two about using positional args in the multiple-inheritance case.

This might help folks with deep inheritance trees at least *notice* that there might be a problem if their test coverage isn't great.

Calling `__init__` with kwargs is generally clearer anyway, *especially* in the presence of potentially confusing orderings as with e.g. diamond inheritance.  So if this pushed pretty much 100% of code using `attrs` to always use kwargs maybe that would be a good idea.

**Comment by hynek** [comment]
Hm that seems a rather harsh thing to do, but an interesting idea.

I’m not ready to go that far, but I think I’ll add a blurb to the newsfragments, encouraging people to use kwargs.

**Pull request merged**
