### PR TITLE
Pass appropriate stacklevel in assoc deprecation warning.

### LINKED ISSUE #208: assoc warning is unhelpful
Currently the warning emitted looks something like this:
```
/home/mithrandi/deployment/virtualenvs/txaws/site-packages/attr/_funcs.py:173: DeprecationWarning: assoc is deprecated and will be removed after 2018/01.
```
I think this should pass an appropriate stacklevel so you can see where the calling code actually is.

### PR DESCRIPTION
**Pull request by mithrandi**
Fixes #208.

I (deliberately) didn't document this change or write a test for it, let me know if that was a mistake.

### CODE REVIEW

**Comment by hynek** [comment]
Could we test somehow that the correct frame is in the warning?

**Comment by mithrandi** [comment]
We could check the source line [reported in the warning](https://docs.pytest.org/en/features/warnings.html#_pytest.recwarn.WarningsRecorder), but that seem somewhat fragile since code moves around all the time. Maybe just check the source file?

**Comment by hynek** [comment]
yeah or method name or something?

**Comment by hynek** [comment]
Does this look good to you?

**Comment by hynek** [comment]
Ugh pytest changed something. Hang on.

**Pull request merged**
