### PR TITLE
[WIP] Frozen attribute support

### PR DESCRIPTION
**Pull request by Tinche**
WIP. Do not merge yet :)

Got initial frozen attribute support working for dict classes using the magic of ✨multiple inheritance✨.

Now to think of something clever for slot classes.

### CODE REVIEW

**Comment by Tinche** [comment]
Alright, we support slot classes too now. the information below is valid for slot classes.

There is zero overhead for `__init__`. 

```
pyperf timeit --rigorous -g --duplicate 10 -s "import attr; B = attr.make_class('B', {'a': attr.ib(frozen=True), 'b': attr.ib(frozen=True)}, slots=True)" 'B(1, 2)'

Before: Mean +- std dev: 410 ns +- 11 ns
After: Mean +- std dev: 409 ns +- 11 ns
```

Unfortunately, attribute access is much slower:
```
pyperf timeit --rigorous -g --duplicate 10 -s "import attr; B = attr.make_class('B', {'a': attr.ib(frozen=True), 'b': attr.ib(frozen=True)}, slots=True); b = B(1, 2)" 'b.b'

Before: Mean +- std dev: 35.8 ns +- 0.8 ns
After: Mean +- std dev: 391 ns +- 17 ns
```

We wrap the original slot descriptor to block mutation, but we pass through access. However, this involves a pure Python method invocation. I don't know how to avoid this :(

**Comment by hynek** [comment]
Nice, factor 10. :|  I don’t think adding RCEs (i.e. write some C) would really help here in any way?  Very generally speaking, I could live with an optional C to speed things up I guess.  I’m just not eager for it.

**Comment by Tinche** [comment]
It would probably help. We would need a customized version of this: https://github.com/python/cpython/blob/fff9a31a91283c39c363af219e595eab7d4da6f7/Objects/descrobject.c#L594

Can Cython help us out here somehow?

**Comment by hynek** [comment]
I'd hope so.  I'm not adding actual C.

**Comment by Tinche** [comment]
Huh, playing around with Cython a little, managed to get the overhead to just ~3x. 25.8 ns to 74.7 ns.

The numbers are a little different since I'm on my work computer atm.

**Comment by hynek** [comment]
Interesting.

Generally I want to give everyone maximum flexibility so the Cython code would go into a separate package (attrs-accel?) and everything has to be implemented also in pure Python.  I bet it’s faster on PyPy anyways. :)

**Comment by Tinche** [comment]
I've left a post on the cython-users mailing list asking for a little advice.

In the mean time, fiddling around, I believe I've managed to get a Cython solution with only 5% overhead (27 ns vs 26 ns).

**Comment by Tinche** [comment]
Here's the link to the post since it finally got approved, just to be thorough. https://groups.google.com/forum/#!topic/cython-users/QaQDNLE-76Y

**Comment by Tinche** [comment]
Ok, confirming that the speed penalty for frozen slot attributes with the Cython accelerator is within 10%.

Non-frozen access: 35.3 ns +- 1.1 ns
Cython frozen access: 38.5 ns +- 1.2 ns
Python frozen access: 368 ns +- 15 ns

I think this makes the idea of having some Cython code in attrs worthwhile, and when we have this infrastructure in place we might want to offer accelerated versions of other components too. I agree all Cython code should be an optimized reimplementation of Python code - native code should be strictly optional.

How do we go about this though? We can have a separate package for Cythonized components, but having a single sdist that cleanly installs even without a C compiler (and just falls back to Python versoins) would be less maintenance - is it possible? We will also need to get Travis to test both versions of the code, and make wheels where we can.

Somewhat unrelated: it occured to me that for frozen dict classes, we can generate a slightly different `__init__`:
```
def __init__(self, a, b):
    __dict__ = self.__dict__
    __dict__['a'] = a
    __dict__['b'] = b
```
This is functionally identical to the way we do it now, with the cached object.__setattr__, right? This approach totally avoids the `__init__` speed penalty for frozen dict classes.

**Comment by hynek** [comment]
This is pretty amazing.  That’s gonna be the flagship feature of attrs 17.2 I reckon.

Maybe we should brainstorm some what makes sense to accelerate etc.

**Comment by smarie** [comment]
@Tinche , just out of curiosity what would be the overhead of transforming all attributes that require either frozen access or have convertors and/or validators, into python `@property` ? It is fairly easy to add a property to a class :

```python
setattr(clazz, attr_name, property(fget=getter_fun, fset=setter_fun))
```

With `getter_fun` being for example a function or lambda with direct access to the field
```python
getter_fun = lambda self: getattr(self, private_attr_name)
```

And `setter_fun` being a function or lambda including frozen access check or conv + validators as usual for non-frozen attrs - the same you have to day in the `__init__` .
Properties seem to now exist for both python 2 and 3.

I don't know how to make that consistent with the base `Attribute` class, maybe `Attribute` could directly inherit from `property`? Or a flavour of attribute (`PropertyAttribute`) could inherit.
Let me know if that is just stupid, I'm relatively new to Python..

(relates to requirement [160](https://github.com/python-attrs/attrs/issues/160))

**Comment by Tinche** [comment]
It's not stupid, the problem is the getter is slow - it involves a pure Python method call.

The current approach is similar to `@property`, but lower level. `@property` under the hood creates a descriptor which invokes the getter and returns the value; we create a descriptor that wraps the existing descriptor on a very low level and delegates getting to it.

**Comment by smarie** [comment]
ok, thanks for the clarification !

**Comment by Infernion** [comment]
Is there any progress on this feature?

**Comment by kdggavkc** [comment]
Bump? Enjoyed reading the history of this request - is this still in the plan for attrs?

**Comment by hynek** [comment]
Closing due to lack of activity (and at this point: unmergeablity – le churn).

**Pull request closed without merging**
