### PR TITLE
Drop support for EOL Python 3.4

### PR DESCRIPTION
**Pull request by hugovk**
Python 3.4 is EOL and no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
3.4 | 2014-03-16 | 2019-03-16

Source: https://en.wikipedia.org/wiki/CPython#Version_history

It's also little used. Here's the pip installs for attrs from PyPI for June 2019:

| category | percent | downloads  |
|----------|--------:|-----------:|
|      3.6 |  36.69% |  5,053,573 |
|      2.7 |  31.95% |  4,400,701 |
|      3.7 |  16.71% |  2,301,996 |
|      3.5 |  11.20% |  1,542,532 |
|      3.4 |   2.58% |    355,665 |
| null     |   0.83% |    113,642 |
|      3.8 |   0.03% |      4,236 |
|      2.6 |   0.00% |        508 |
|      3.3 |   0.00% |        394 |
|      3.9 |   0.00% |         55 |
|      3.2 |   0.00% |         37 |
|      2.8 |   0.00% |          2 |
|      3.1 |   0.00% |          1 |
| Total    |         | 13,773,342 |

Source: `pypistats python_minor attrs --last-month # pip install pypistats`

# Pull Request Check List

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] Added **tests** for changed code.
- [x] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/strategies.py).
- [x] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [x] ...and used in the stub test file `tests/typing_example.py`.
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
- [x] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/master/changelog.d).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by hugovk** [comment]
> * Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/master/changelog.d) [](/python-attrs/attrs/blob/HEAD@{2019-07-16T10:55:50Z}/changelog.d).

What sort of `554.(change|deprecation|breaking).rst` entry would you like?

**Comment by hugovk** [comment]
Coverage dropped as a Python 3.8-only line is missing from the report, because the 3.8 coverage wasn't uploaded due to a network error:

```
    Pinging Codecov...
Error:‌ HTTPSConnectionPool(host=&#x27;codecov.io&#x27;, port=443): Max retries exceeded with url: &#x2F;upload&#x2F;v4?commit=35363fd29056a8932715e1fff70a04f1ff408596&amp;branch=HEAD&amp;token=***&amp;yaml=codecov.yml&amp;package=py2.0.15 (Caused by NewConnectionError(&#x27;&lt;requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f71803fc520&gt;: Failed to establish a new connection: [Errno 110] Connection timed out&#x27;))‌
```

https://attrs.visualstudio.com/attrs/_build/results?buildId=178&view=logs

Hopefully the next build with the news fragment will be successful.

**Comment by hynek** [comment]
We're not explicit about this, but our [Python 2](https://www.attrs.org/en/stable/python-2.html) statement kinda applies to this too: we will keep supporting versions as long as it's not too much work for us. Currently, there isn't much for us to win from dropping 3.4 so I wouldn't rush it.

And yes, the codecov thing is super frustrating. I don't know what's happening there but we might have to look into coveralls again. :(

**Comment by hugovk** [comment]
Sure, as this PR shows the only real benefit is removing it from the CI, and it only takes a minute which is hardly noticeable with AP's 10 parallel jobs!

**Pull request closed without merging**
