### PR TITLE
Improve sentence parsing

### PR DESCRIPTION
**Pull request by skorokithakis**
I've always parsed this sentence as "attrs comes with serious, business aliases". I just realized you probably meant srs bzns aliases and figured I'd clarify.

# Pull Request Check List

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] Added **tests** for changed code.
- [x] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/strategies.py).
- [x] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [x] ...and used in the stub test file `tests/typing_example.py`.
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
- [x] Documentation in `.rst` files is written using [semantic newlines](http://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/master/changelog.d).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by wsanchez** [comment]
Well, this requires research.

Grammar Monster [seems to agree](https://www.grammar-monster.com/lessons/hyphens_in_compound_adjectives.htm), says that a compound adjective (as opposed to two adjectives that each apply) should be hyphenated for clarity… and with a name like Grammar Monster, it's hard to argue.

So the question is whether @hynek meant that the aliases are both serious aliases and business aliases or whether he meant that they are "serious business" aliases.  I've always assumed the latter, in which case this PR is correct.

I'll leave it to @hynek to confirm.  :-)

**Comment by skorokithakis** [comment]
Thank you for the extensive research, this echoes my thinking perfectly. We cannot make this change lightheartedly, so I salute your efforts to that end.

**Comment by hynek** [comment]
Obviously, I meant srs bzns duh. ;)

**Comment by hynek** [comment]
Thanks!

**Pull request merged**
