### PR TITLE
Final classvars

### PR DESCRIPTION
**Pull request by Tinche**
Treat `Final` attributes as classvars as default.

### CODE REVIEW

**Comment by Tinche** [comment]
@hynek CPython gets typing_extensions by default, but PyPy doesn't?

**Comment by Tinche** [comment]
I spoke too soon, `Final` instance vars in attrs classes don't work with Mypy. So it's a mess.

**Comment by hynek** [comment]
Are you gonna finish this up or can I close it?

**Comment by Tinche** [comment]
This needs non-trivial Mypy work, so unsure.

**Comment by hynek** [comment]
Closing it for now, since it's already full of conflicts. I presume you have your branch somewhere local?

**Comment by Tinche** [comment]
Yeah, we can clean up the branch. I'll pick it up again someday.

**Comment by Tinche** [comment]
Actually let me restore the branch for a sec so I can back it up on this computer.

**Pull request closed without merging**
