### PR TITLE
Fix minor stub issues

### PR DESCRIPTION
**Pull request by hynek**
I've tried running ruff over attrs and these issues seem legit.

### CODE REVIEW

**Comment by hynek** [comment]
uh what's with the checks? did i screw something up when adding environments to the deploy stuff? @webknjaz? 😇

https://www.githubstatus.com says all is dandy

**Review by Tinche — APPROVED** [review]

**Comment by webknjaz** [comment]
> uh what's with the checks? did i screw something up when adding environments to the deploy stuff? @webknjaz? innocent
> 
> [githubstatus.com](https://www.githubstatus.com) says all is dandy

I haven't seen what was happening when you tagged me, but sometimes GitHub is just drunk. Their eventually consistent event delivery system sometimes fails to propagate events and doesn't re-deliver them after having platform troubles.
It's also worth noting that GitHub doesn't always update the status website. Sometimes there are issues with GHA or unicorns that are short-lasting and that doesn't end up on the status page.
Looking at https://www.githubstatus.com/history, I see that today there were two reported problems with Actions specifically a bit earlier than the PR's timestamp, it seems.

The environments wouldn't affect this because they are applied to jobs in another workflow, and you'd have notifications about the approval requests in your inbox. Besides, workflow definition parsing issues manifest themselves differently — there's a weird error message on the workflow run page with almost zero context on what's broken.

**Comment by hynek** [comment]
Well, it didn't work because I didn't know that there's a separate hostname for uploads. _sigh_.

https://github.com/python-attrs/attrs/commit/f04dce20f1aaa89a6fa888e7a07e133f434ac602

**Comment by hynek** [comment]
They just wouldn't start – it looked like my problems in my package builder where CI wouldn't run on PRs.

**Pull request merged**
