### PR TITLE
Fix type annotations for converter types, considering the Converter class

### PR DESCRIPTION
**Pull request by filbranden**
# Summary

A converter can either be a callable with a single argument or an instance of the Converter class, fix the type annotation to allow both cases everywhere `_ConverterType` is used

Also update `field()` and `attr.ib()` which are able to take a list or tuple of converters as an implicit pipe, add type annotations for that syntax

# Pull Request Check List

- [x] Do **not** open pull requests from your `main` branch – **use a separate branch**!
  - There's a ton of footguns waiting if you don't heed this warning. You can still go back to your project, create a branch from your main branch, push it, and open the pull request from the new branch.
  - This is not a pre-requisite for your pull request to be accepted, but **you have been warned**.
- [x] Added **tests** for changed code.
  Our CI fails if coverage is not 100%.
- N/A New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- [x] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [x] ...and used in the stub test file `tests/typing_example.py`.
    - N/A If they've been added to `attr/__init__.pyi`, they've *also* been re-imported in `attrs/__init__.pyi`.
- N/A Updated **documentation** for changed code.
- N/A Documentation in `.rst` and `.md` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/main/changelog.d).
- [x] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

### CODE REVIEW

**Comment by filbranden** [comment]
@hynek Would you kindly take a look whenever possible? Thanks!

**Review by Tinche — APPROVED** [review]
LGTM from what I can follow

**Comment by hynek** [comment]
It looks to me like worthy a changelog entry because apparently converters are better supported now? 🤔

**Comment by filbranden** [comment]
I believe Converters are already mentioned in the changelog for 24.1.0:

"It is now possible to wrap a converter into an `attrs.Converter` and get the current instance and/or the current field definition passed into the converter callable.

Note that this is not supported by any type checker, yet. https://github.com/python-attrs/attrs/issues/1267"

This just fixes some type annotations but I believe full type checker support would need some mypy changes (see commented out code) so not sure how much is worth mentioning in a changelog.

Having said that, feel free to add a note if you'd like 😃

**Pull request merged**
