### PR TITLE
RFC: Bring in the attrs plugin from mypy

### PR DESCRIPTION
**Pull request by euresti**
Note: The lint tests are failing because mypy code is 120 vs 79 here.  I plan to fix those but there are some bikesheds to decide first:

1. Is the incantation:
```
[mypy]
plugins = attr.mypy
```
what we want?  It's how https://github.com/samuelcolvin/pydantic/tree/master/pydantic ships its plugin and it seemed neater than how sqlalchemy-stubs does it.  (They ship a separate module but it looks like this)
```
[mypy]
plugins = sqlmypy
```

2. I know people have been clamoring to fix the "How do I make my method an attr.s method". Are we ok with landing this as is and then in a later revision adding that, possibly breaking whatever hacks people have already written?  i.e. do we need to worry about any backwards compatibility issues?
3. Do we wish to preserve any of the history from the mypy repo?  
4. Any licensing issues?

Tagging the following people since you contributed to the attrs plugin on mypy:
@ilevkivskyi @msullivan @JukkaL @Zac-HD @tkukushkin @Bogdanp
@natemcmaster @Michael0x2a @markusschmaus @ceh

Please let me know if this is a huge problem.  And let me know if you want me to somehow preserve the history of the file changes (or just your contribution).  This is completely new territory for me.  I'm not trying to just steal people's hard work. I'm just trying to make it easier for attrs to maintain the plugin outside of the regular mypy release cycle.

# Pull Request Check List

This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.  If your pull request is a documentation fix or a trivial typo, feel free to delete the whole thing.

- [ ] Added **tests** for changed code.
- [ ] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/strategies.py).
- [ ] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [ ] ...and used in the stub test file `tests/typing_example.py`.
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in our [``__init__.py``](https://github.com/python-attrs/attrs/blob/master/src/attr/__init__.py) file.
- [ ] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/master/changelog.d).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by Tinche** [comment]
> I know people have been clamoring to fix the "How do I make my method an attr.s method". Are we ok with landing this as is and then in a later revision adding that, possibly breaking whatever hacks people have already written? i.e. do we need to worry about any backwards compatibility issues?

As one of the people clamoring for this I think taking a little while to get this right is more important than backwards comp right now.

**Comment by hynek** [comment]
> I know people have been clamoring to fix the "How do I make my method an attr.s method". Are we ok with landing this as is and then in a later revision adding that, possibly breaking whatever hacks people have already written? i.e. do we need to worry about any backwards compatibility issues?

Unfortunately I'm busy until next year, but could you elaborate what this means please? Would embracing this break my attrs-ng plugin?

(I like attr.mypy better I think)

**Comment by euresti** [comment]
> Would embracing this break my attrs-ng plugin?
Yes and no.  Your plugin currently does this:

```
from mypy.plugin import Plugin
from mypy.plugins.attrs import attr_attrib_makers, attr_dataclass_makers

attr_dataclass_makers.add("attr.define")
attr_dataclass_makers.add("attr.mutable")
attr_dataclass_makers.add("attr.frozen")
attr_attrib_makers.add("attr.field")
```

Which will pretty much do nothing because it's trying to patch `mypy.plugins.attrs`
However the plugin in `attr.mypy` actually supports attrs-NG so there's no need for this.  

But what I'm talking about is the `attr_dataclass_makers.add("attr.define")` itself.  Maybe we change it so that you can configure it using mypy.ini config file or some other thing like `register_attr_dataclass_maker(...)` or something like that.  How important is it to preserve this "hack" for backwards compatibility.  (And do we even want to answer this right now?)

**Comment by hynek** [comment]
I really don't want to break anything and that would actually break almost all of my work projects. :D

But let's back up a little. If I understand it correctly, people will have to opt **in** to use our plugin and otherwise they'll fall back to mypy, is that correct? That would mean that we wouldn't break anything and people would have to touch their mypy.ini anyways, correct?

I mean mid-term we could ask mypy to automatically recognize _our_ plugin, but ISTM we have some leeway thanks to this?

**Comment by euresti** [comment]
> I really don't want to break anything and that would actually break almost all of my work projects. :D

I think I lost the meaning of "that" in this sentence.  Could you elaborate what would break almost all your work projects?

> But let's back up a little. If I understand it correctly, people will have to opt in to use our plugin and otherwise they'll fall back to mypy, is that correct? That would mean that we wouldn't break anything and people would have to touch their mypy.ini anyways, correct?

We could also remove the plugin from mypy.  In fact we should otherwise we'll get version skew bug reports which would be really annoying.  In mypy we could error out when it sees an attr.s and tell you to install the plugin.  

> I mean mid-term we could ask mypy to automatically recognize our plugin, but ISTM we have some leeway thanks to this?

Are you suggesting that something in mypy detect that the code is using attrs and load our plugin?   This could be possible but I think it might have a lot of weird issues because it changes when our plugin gets intialized by the mypy plugin system and who knows what else.

Is having to modify mypy.ini a deal breaker?

**Comment by JukkaL** [comment]
I don't have a strong opinion on this, but I have a few concerns:

* The plugin uses a bunch of undocumented, internal mypy APIs that are not necessarily stable. It's possible that updating mypy could break the attrs plugin (at least older versions of the plugin, if we are careful to keep attrs and mypy in sync). This is my main concern. Maybe we'd continue to test the plugin in mypy CI to catch regressions -- but this would effectively turn these APIs into stable APIs.
* It may become unclear which mypy versions are supported by the plugin, and the plugin may accidentally break on older mypy versions that are still in active use. It would be nice if attrs CI could test the plugin using the oldest supported mypy version and the latest one. If somebody tries to use the plugin on an unsupported mypy version, the plugin probably shouldn't crash but suggest updating to a more recent mypy version.
* As proposed above, mypy should start suggesting to install attrs and enabling the plugin, as otherwise users could silently lose some type checking precision. In case a mypy user doesn't want to use the plugin shipped with attrs for some reason, we can make it possible to ignore the error by giving it a unique mypy error code (this needs to be documented, however).

**Comment by hynek** [comment]
Hey Jukka, thanks for chiming in!

> Maybe we'd continue to test the plugin in mypy CI to catch regressions -- but this would effectively turn these APIs into stable APIs.

Correct me if I'm wrong, but aren't they de-facto stable already? How are pydantic and sqlalchemy stubs handle this?

> It would be nice if attrs CI could test the plugin using the oldest supported mypy version and the latest one. If somebody tries to use the plugin on an unsupported mypy version, the plugin probably shouldn't crash but suggest updating to a more recent mypy version.

That seems reasonable.

> As proposed above, mypy should start suggesting to install attrs and enabling the plugin, as otherwise users could silently lose some type checking precision. In case a mypy user doesn't want to use the plugin shipped with attrs for some reason, we can make it possible to ignore the error by giving it a unique mypy error code (this needs to be documented, however).

Long-term I would really like to make it opt-out, not opt-in. I.e. mypy picks up attrs's plugin automatically and there should be a switch to disable that – would you find that reasonable?

**Comment by hynek** [comment]
> > I really don't want to break anything and that would actually break almost all of my work projects. :D
> I think I lost the meaning of "that" in this sentence. Could you elaborate what would break almost all your work projects?

Not having _some_ attrs plugin active by default.

> > I mean mid-term we could ask mypy to automatically recognize our plugin, but ISTM we have some leeway thanks to this?
> 
> Are you suggesting that something in mypy detect that the code is using attrs and load our plugin? This could be possible but I think it might have a lot of weird issues because it changes when our plugin gets intialized by the mypy plugin system and who knows what else.

Yeah, that's what I'm suggesting. If it's not possible, so be it but it would be really nice if we could make that work.

> Is having to modify mypy.ini a deal breaker?

Not a deal breaker per se, but it's definitely a usability regression (especially over dataclasses) that I would like to get rid of eventually. Also it's breaking backward-compat.

**Pull request closed without merging**
