### PR TITLE
Fix bug in resolve_types with subclasses

### LINKED ISSUE #842: `attr.resolve_types` caches badly with inheritence
Reproduction case:

```py
from __future__ import annotations

import attr

@attr.define()
class A:
  n: int

@attr.define()
class B(A):
  pass

attr.resolve_types(A)
attr.resolve_types(B)

print(attr.fields(B))
```

I believe this is because `B` is somehow inheriting `A`'s `__attrs_types_resolved__`, even though it gets set later -- which means that it never had its types resolved, but it thinks it has.

This came up when I was using cattrs (I raised an issue there about a trouble I had debugging too :^), which means I do not control the resolution order of types without applying a `attr.resolve_types` decorator to every class (which might not work -- I'm not sure all my class declarations are in order either...)

### PR DESCRIPTION
**Pull request by euresti**
# Pull Request Check List

This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.  If your pull request is a documentation fix or a trivial typo, feel free to delete the whole thing.

Fixes #842

- [x] Added **tests** for changed code.
- [ ] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- [ ] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [ ] ...and used in the stub test file `tests/typing_example.py`.
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in our [``__init__.py``](https://github.com/python-attrs/attrs/blob/main/src/attr/__init__.py) file.
- [ ] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/main/changelog.d).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by euresti** [comment]
Does this type of change need a changelog entry?

**Comment by hynek** [comment]
Thanks for stepping up real quick as usual!

Yeah I think it’s worth mentioning!

For every bug report there’s 10 people who didn’t bother.

also pls `src/attr/_funcs.py:390:80: E501 line too long (82 > 79 characters)` :)

**Comment by euresti** [comment]
Ok.  Gotta go make breakfast but I'll get the changelog in after that.

**Comment by hynek** [comment]
Oh god why is codecov angry. If you don’t have time for it, I’ll check once I’m back from Italy and off phone-only.

**Comment by euresti** [comment]
Oh it's because nothing tests the "cached" flow.

**Comment by euresti** [comment]
Sorry for all the lint failures. I don't have python 3.10 on my machine and you can only run pre-commit or tox -e lint if you have python 3.10.

**Comment by euresti** [comment]
Ok I have no idea why codecov is complainign about this:
image

https://app.codecov.io/gh/python-attrs/attrs/compare/843/tree/src/attr/_compat.py

**Comment by hynek** [comment]
It was complaining about the same thing on #840 and then magically stopped…some codecov flakiness? :-/

**Comment by euresti** [comment]
It passed!

**Comment by hynek** [comment]
🤡

**Review by hynek — APPROVED** [review]

**Comment by hynek** [comment]
Thanks for the quick turnarounds!

**Pull request merged**
