### PR TITLE
[RFC] Enhancement/one of validator

### PR DESCRIPTION
**Pull request by dieb**
Hello there!

I wrote this for one of my projects and I thought it could be useful to others too. This is a validator called `in_(options)` that allows you to check if the value is within the allowed values. In my particular case it was useful to test things like `in_(POSSIBLE_CHOICES)`, `in_(Animals)`, etc.

Example:

```python
US_STATES = ['AB', 'AG', 'AK', ...]

@attr(slots=True)
class Location(object):
    city = attr.ib(validator=instance_of(str))
    state = attr.ib(validator=in_(US_STATES))
```

I was wondering if you had any thoughts and whether it would make sense to add it to attrs. If that's the case, I'd be more than happy to adjust the code with your suggestions.

Thanks!

# Pull Request Check List

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](http://www.attrs.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [ ] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/utils.py).
- [x] Updated **documentation** for changed code.
- [ ] Documentation in `.rst` files is written using [semantic newlines](http://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
- [x] Changes (and possible deprecations) are documented in [`CHANGELOG.rst`](https://github.com/python-attrs/attrs/blob/master/CHANGELOG.rst).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by hynek** [comment]
This seems like a good idea however the naming (and docstring) seems too restrictive given the implementation.  Something like `is_in(possible_values)` seems more natural to me?

**Comment by dieb** [comment]
`is_in` sounds good. Given that other validators are single words (e.g. `optional`), what do you think about `within`?

**Comment by hynek** [comment]
@glyph try to talk me out of calling it `in_()` please.   We have precedents in sqlchemistry. ;)

**Comment by glyph** [comment]
`found_in`?

**Comment by hynek** [comment]
Since we’re going for `and_()` in #186 and ppl are used to them from sqlalchemy, please go for `in_()`.

**Comment by hynek** [comment]
(I cannot promise this will make it into 17.1 b/c I need to get it out ASAP but it’s possible.  If you want to raise your chances, please double check CONTRIBUTING.rst; especially re: test docstrings.)

**Comment by dieb** [comment]
Just updated it to `in_()`.

**Comment by hynek** [comment]
Thanks, I’ve made some small adjustments.

**Comment by dieb** [comment]
Thanks!

**Comment by dieb** [comment]
I just noticed I forgot to add `in_()` to `__all__`, I'll submit a PR later on.

**Pull request merged**
